development:
  adapter: postgresql
  encoding: unicode
  database: master_hunter_develoment
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: master_hunter_test
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: master_hunter_production
  pool: 5
  username: postgres
  password:
